# Generated by Django 3.2.4 on 2021-08-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210818_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.TextField()),
                ('course_level', models.CharField(choices=[('H', 'Form Four Certificate'), ('DE', 'Degree'), ('DI', 'Diploma'), ('M', 'Masters'), ('DO', 'PHD')], default='DE', max_length=10)),
            ],
            options={
                'unique_together': {('course_name', 'course_level')},
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='completed_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.course'),
        ),
    ]
