# Generated by Django 3.2.4 on 2021-08-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210818_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, to='employee.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employer'),
        ),
    ]
