# Generated by Django 3.2.4 on 2021-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210819_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_numbers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_numbers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
