# Generated by Django 3.2.4 on 2021-09-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210907_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='sub_department',
            new_name='sub_departments',
        ),
    ]
